### ISSUE TITLE
96 Mutation Profile error

### ISSUE THREAD

**Issue by apchumangenomics** [UMCUGenetics/MutationalPatterns#13]
Hi, I am running into the error as follows when using the mut_matrix function;
'Error in for (vcf in vcf_list) { : invalid for() loop sequence'
I get this error with my data or the provided sample data.
Thanks for any help

**Comment by roelj** [comment]
Hi @apchumangenomics .

Thanks for reporting the issue.

It looks like issue https://github.com/UMCUGenetics/MutationalPatterns/issues/11.
You can use the solutions provided there, or wait for the next Bioconductor release in which a fix has been made.

The new Bioconductor release is scheduled for today:
http://bioconductor.org/developers/release-schedule/

Please let me know whether this solves your problem.

**Comment by apchumangenomics** [comment]
Hi @roelj,
Thanks for the response. Yes, its the exact same error. I too found the GitHub option addressed the issue. Thank you very much for your time. Sorry for not giving the closed issues a proper search.
