### ISSUE TITLE
plot_spectrum error bar warning

### ISSUE THREAD

**Issue by MyrtheJ** [UMCUGenetics/MutationalPatterns#15]
Hi!

I am using the plot_spectrum function to plot the spectrum of 10 samples by 'sample_name' (CT=T).
I will get the following warning:
Warning message:
Removed 70 rows containing missing values (geom_errorbar).
Obviously, it could not generate an errorbar for the 7 bars (mutation types) based on single samples. 
Is there a way to remove this warning if actually nothing is going wrong? This example was easy to calculate, but when the numbers get bigger it is more difficult to see whether there is actually an error, or whether this is what you would expect.

Thank you!
Myrthe Jager

**Comment by FrancisBlokzijl** [comment]
Hi Myrthe,

Thanks for your suggestion. I've changed the warning message to "No standard deviation error bars can be plotted, because there is only one sample per mutation spectrum" in the develop branch. We will include this in the new release later this year.

Thanks
Francis
