### ISSUE TITLE
issue with mut_matrix function

### ISSUE THREAD

**Issue by sbaheti84** [UMCUGenetics/MutationalPatterns#16]
I am trying to run this package to get  96 Mutation profile but getting this error with real and test data supplied with the package.

mut_mat <- mut_matrix(vcf_list = vcfs, ref_genome = ref_genome)
Error in for (vcf in vcf_list) { : invalid for() loop sequence

I am not sure what is the problem, could you please look into this 

Thanks !

**Comment by roelj** [comment]
Hi @sbaheti84.  Thanks for reporting the issue.

Because you closed the issue I suppose you've either upgraded to the latest version from Bioconductor, or you have seen the solution at:
https://github.com/UMCUGenetics/MutationalPatterns/issues/11

Thanks!

**Comment by sbaheti84** [comment]
yes, i looked at the previous thread and the issue was resolved. Thanks !
