### ISSUE TITLE
can mutationpattern handle indel mutations?

### ISSUE THREAD

**Issue by tangwei1129** [UMCUGenetics/MutationalPatterns#17]
Hi, I wonder if mutationpattern can deal with indel mutations besides A/C/T/G single base change.
and can the pkg extends to chrX chrY and chrM?

**Comment by FrancisBlokzijl** [comment]
Hi Tangwei,

MutationalPatterns is for the analysis of SNVs and not for indels.
You can include the sex and mitochondrial chromosomes in your analysis, by setting the _group_ parameter in the read_vcfs_as_granges function. For more details see: 
?read_vcfs_as_granges

Kind regards,
Francis

**Comment by FrancisBlokzijl** [comment]
For these kind of fundamental research questions I would like to refer you to https://www.biostars.org/
