### ISSUE TITLE
Whole Genome Versus Exome - signature extraction

### ISSUE THREAD

**Issue by apchumangenomics** [UMCUGenetics/MutationalPatterns#18]
To Whom It May Concern,

When extracting signatures from exome data, do you have to take into consideration  trinucleotide frequency as the differs between whole genome and exome? If so, how would one go about doing so?

Thanks for any help,
Maurice

**Comment by FrancisBlokzijl** [comment]
Dear Maurice,

Typically absolute frequencies are used for mutational signature extraction without normalization for the trinucleotide content. Check out this issue for a discussion on this:
https://github.com/raerose01/deconstructSigs/issues/2

It really depends on your research question whether you want to correct for the trinucleotide frequencies. Keep in mind that even if you do, different mutational processes are active in exomes versus whole genomes.

Good luck.

Best,
Francis

**Comment by roelj** [comment]
I'm closing this because the original question has been addressed, and there hasn't been a follow-up in two months.

Thanks for contacting us!
