### ISSUE TITLE
Installing MutationalPatterns

### ISSUE THREAD

**Issue by AxelRosendahlHuber** [UMCUGenetics/MutationalPatterns#19]
During Installing MutationalPatterns does not automatically load packages: 'Rcurl', 'stringi'

**Comment by roelj** [comment]
Hello @AxelRosendahlHuber,

That's right.  These are not direct dependencies for MutationalPatterns.
What problem are you running into?

**Comment by AxelRosendahlHuber** [comment]
Hoi Roel,

Een student van mij wilde de functie plot_contribution_heatmap gebruiken maar kon Mutationalpatterns  niet installeren zonder Rcurl en stringi.
Vandaar mijn bericht.

Groet, Axel

**Comment by roelj** [comment]
Dear Axel,

Thanks for reporting the bug.  Unfortunately, I don't think we can (or should) address this from MutationalPatterns.  Did the installation of either `RCurl` or `stringi` fail?  They are supposed to be install automatically.

A quick look at the dependencies indicates that the dependency path towards `RCurl` is: `MutationalPatterns` -> `VariantAnnotation` -> `GenomicFeatures` -> `biomaRt` -> `httr` -> `RCurl`

So, does installing `VariantAnnotation` work?

Thanks for your time.

Kind regards,
Roel

**Comment by AxelRosendahlHuber** [comment]
Hi Roel,

Thanks for the response. Installing Rcul and stringi manually worked in the end.

Best,

Axel

**Comment by roelj** [comment]
Thanks for your reply, and good to hear that it worked eventually.
