### ISSUE TITLE
Colors parameter in plot_contribution

### ISSUE THREAD

**Issue by jdeligt** [UMCUGenetics/MutationalPatterns#2]
When plotting different sample sets you could get different colors for the same signature.

**Comment by FrancisBlokzijl** [comment]
Hey Joep,

Is this still an issue? I'm not sure I understand the problem, do you mean in different analyses?
What is your request?

Thanks!

Francis

**Comment by roelj** [comment]
I added a color palette parameter to `plot_contribution` in 58ca5ac7cb9a8a6a1e217fc0da5f0ecdfc6df3cd.  I think this allows one to avoid this problem.
