### ISSUE TITLE
Mutational patterns in Mouse

### ISSUE THREAD

**Issue by fitbio** [UMCUGenetics/MutationalPatterns#21]
Can mutational patterns be used for analysing mouse whole genome data.? If so will the trinucleotide pattern is same as observed in hg19?

**Comment by roelj** [comment]
Yes, you can use it on mouse WGS data.  Make sure to use the appropriate mouse reference genome when loading your data.

I don't know whether the trinucleotide pattern is the same.

**Comment by fitbio** [comment]
Thank you for your quick reply. Just one final question. I used Whole genome  Human cancer data for my analysis. So I do not need to change any parameters for whole genome samples right?

**Comment by roelj** [comment]
MutationalPatterns doesn't do any filtering on your data (other than removing anything that isn't a SNP), so there are not many parameters to set.  Make sure to pick the right reference genome.

Also, have a look at the vignette.  It explains more in-depth what each function does and when to use it.

**Comment by fitbio** [comment]
Thank you. It was helpful
