### ISSUE TITLE
 Find optimal contribution of known signatures

### ISSUE THREAD

**Issue by sadafambreen** [UMCUGenetics/MutationalPatterns#24]
Hi,
I have used MutationalPatterns for my own data. But, when i tried to plot mutational profile of the  COSMIC signatures. I got error. Can you help me to solve this problem. As, i write new_order = match(row.names(mut_mat), cancer_signatures$Somatic.Mutation.Type).  The new file contain ''NA''  all columns and rows.
 I thought, it can be error from my data. But, by using example data, i am getting  same error.  It seems simple, but i am unable to solve it?

**Comment by roelj** [comment]
Can you provide the code you ran, and the exact error message, so I can try to reproduce the error?

Thanks!

**Comment by sadafambreen** [comment]
> sp_url <- paste("http://cancer.sanger.ac.uk/cancergenome/assets/",
+ "signatures_probabilities.txt", sep = "")
> cancer_signatures = read.table(sp_url, sep = "\t", header = TRUE)
> mut_mat <- readRDS(system.file("states/mut_mat_data.rds",
+ package="MutationalPatterns"))
> order = match(row.names(mut_mat), cancer_signatures$Somatic.Mutation.Type)
> cancer_signatures = cancer_signatures[order,]
> cancer_signatures = as.matrix(cancer_signatures[,4:33])
> colnames(cancer_signatures) = as.character(1:30)
> cos_sim_matrix(mut_mat, cancer_signatures)
Error in cos_sim_matrix(mut_mat, cancer_signatures) :
  could not find function "cos_sim_matrix"
> cos_sim_matrix(mut_mat, cancer_signatures)
Error in cos_sim_matrix(mut_mat, cancer_signatures) :
  could not find function "cos_sim_matrix"
> cancer_signatures
       1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
NA    NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
NA.1  NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

**Comment by sadafambreen** [comment]
I am getting the  error, at this step:  Match the order to MutationalPatterns standard of mutation matrix.
> new_order = match(row.names(mut_mat), cancer_signatures$Somatic.Mutation.Type)
> cancer_signatures = cancer_signatures[as.vector(new_order),]
> row.names(cancer_signatures) = cancer_signatures$Somatic.Mutation.Type
Warning: non-unique values when setting 'row.names':
Error in `row.names<-.data.frame`(`*tmp*`, value = c(NA_integer_, NA_integer_,  :
  duplicate 'row.names' are not allowed

**Comment by roelj** [comment]
What version of the package are you using?  You can find that using
```
sessionInfo()
```

**Comment by sadafambreen** [comment]
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

**Comment by roelj** [comment]
Can you provide *all* output of the `sessionInfo()` command?  Or at least find the version of `MutationalPatterns` there?

**Comment by sadafambreen** [comment]
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /software/biosoft/software/Rsoft/R3.4/lib64/R/lib/libRblas.so
LAPACK: /software/biosoft/software/Rsoft/R3.4/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] gtools_3.5.0
 [2] gridExtra_2.3
 [3] doParallel_1.0.11
 [4] iterators_1.0.9
 [5] foreach_1.4.4
 [6] BSgenome.Cfamiliaris.UCSC.canFam3_1.4.0
 [7] BSgenome_1.44.2
 **[8] MutationalPatterns_1.2.1**
 [9] signeR_1.2.2
[10] NMF_0.21.0
[11] cluster_2.0.7-1
[12] rngtools_1.3.1
[13] pkgmaker_0.27
[14] registry_0.5
[15] rtracklayer_1.36.6
[16] VariantAnnotation_1.22.3
[17] Rsamtools_1.28.0
[18] Biostrings_2.44.2
[19] XVector_0.16.0
[20] SummarizedExperiment_1.6.5
[21] DelayedArray_0.2.7
[22] matrixStats_0.53.1
[23] Biobase_2.36.2
[24] GenomicRanges_1.28.6
[25] GenomeInfoDb_1.12.3
[26] IRanges_2.10.5
[27] S4Vectors_0.14.7
[28] BiocGenerics_0.22.1
[29] BiocInstaller_1.26.1

**Comment by roelj** [comment]
We've had several changes to avoid duplicate rownames between version 1.2.1 and version 1.6.1.
Could you try updating the package?

**Comment by sadafambreen** [comment]
Yes, Thank you. Problem is solved. I should use updated version.
