### ISSUE TITLE
side colors in the heatmap ?

### ISSUE THREAD

**Issue by cedricvanm** [UMCUGenetics/MutationalPatterns#26]
Hi, 

thanks for this great package!
In the heatmap of the contributions of each signature, is it possible to add a color to each sample ? This could help see if the clustering correlates with e.g. the histology of the tumor sample.

In gplot, the function heatmap.2 has the parameter "rowsidecolors" and "colsidecolors" to do this.

Is there a way to do this in the function plot_contribution_heatmap ?

Thanks for the answer,
Cedric

**Comment by cedricvanm** [comment]
great you could answer so fast. 
Unfortunately, I'm not an R expert, so if you have some difficulties to figure it out, I'll be of very little help ;)

I tried this : 
``
x1 <- as.matrix(t(fit_res_T$contribution))
``

And created a vector matching the histology of each sample to a color (here : 5 different histologies).
``
typecolors<-rainbow(5)[as.numeric(as.factor(clinic$histology))]
``

``
library(gplots)
heatmap.2(x1, 
          distfun=function(x) as.dist(1-cor(t(x))), 
          hclustfun=function(x)hclust(x,method="ward.D"), 
          trace="none", 
          RowSideColors=typecolors, 
          col=my_palette, 
          margins = c(6,6), 
          density.info="none")
``

But in the figure, the colors do not match anymore with the samples.
I guess I should reorder the vector, but I don't know how.
Any idea ?

Besides, I saw that in your great Science paper of 2017, there was a colorcode for the MSI clones. Was it edited afterwards by a figure software ?

All the best,
Cedric

**Comment by FrancisBlokzijl** [comment]
Hi Cedric,

In the Science paper we added the sample colors manually with Illustrator.

For more general R questions I would like to refer to forums such as stackoverflow and biostars.

Good luck!

Best,
Francis
