### ISSUE TITLE
Fit to new signatures

### ISSUE THREAD

**Issue by MyrtheJ** [UMCUGenetics/MutationalPatterns#28]
Hi!

Currently, the 'fit_to_signatures' function can only be used on data with 96 mutation types. However, there are also new signatures with TCstrand information. Could you add a function with enables fitting the profiles to 192 mutation types?

Thank you!
Myrthe

**Comment by FrancisBlokzijl** [comment]
Hi Myrthe!

Good point! We have now changed the function such that it can take signatures with any number of features, for example transcriptional strand bias signatures with 192 features.

Could you please let us know if it works for you? It's in the master branch.

Best,
Francis

**Comment by FrancisBlokzijl** [comment]
Hi Myrthe,

Could you please let us know if your issue is solved with these changes?

Best,
Francis

**Comment by MyrtheJ** [comment]
Hi Francis,

Whoops sorry. Indeed it seems to work now! Thanks!

Myrthe
