### ISSUE TITLE
Support for latest (49) signatures?

### ISSUE THREAD

**Issue by sigven** [UMCUGenetics/MutationalPatterns#29]
Hi,

There are now a new set of signatures that have been assembled from ICGC-PCAWG:
https://www.biorxiv.org/content/biorxiv/early/2018/05/15/322859.full.pdf

Are you planning to support a fit to these signatures, and not only the 30 COSMIC signatures?

Sigve

**Comment by roelj** [comment]
Hi,

There's nothing specifically fitting to the COSMIC signatures, other than the signature probabilities file.  So if you prepare a new signature probabilities file and change this step in the manual:
```
> sp_url <- paste("https://cancer.sanger.ac.uk/cancergenome/assets/",+                 "signatures_probabilities.txt", sep = "")
```

You can fit to the new signatures.

We also recently changed `fit_to_signatures` to allow for mutation matrices with other sizes than 64.  This hasn't landed in Bioconductor yet (it will do soon), but you can use the Github repository's master branch to use this.

I hope this helps.

**Comment by sigven** [comment]
Thanks a lot. This is very helpful, indeed!

best,
Sigve
