### ISSUE TITLE
Number of cores for cluster

### ISSUE THREAD

**Issue by andreyurch** [UMCUGenetics/MutationalPatterns#34]
Dear developers,

Thank you very much for the useful tool. I found a problem working on the computer cluster with large VCF dataset. It seems that the numbers of cores used by read_vcfs_as_granges(),
mut_matrix() and others are defined by the detectCores() function. But, if one uses a computer cluster with 96 cores in total but only 10 allowed per user, he will encounter a problem because the MutationalPatterns will try to use all 96 instead of permitted 10. I think it would be great to add the number of cores as a predefined value which the user can set up. 

Best regards,
Andrey

**Comment by FrancisBlokzijl** [comment]
Dear Andrey,

This is a good point! We will add a "n_cores" parameter to this function. We will let you know when it's done!

Kind regards,
Francis

**Comment by roelj** [comment]
We've added the n_cores parameters in https://github.com/UMCUGenetics/MutationalPatterns/commit/283570e84132416764ebbc739bf44f6edc982791 and https://github.com/UMCUGenetics/MutationalPatterns/commit/d18e87c1522b025c9bf5d9f2881343b3db9adf53.

@andreyurch Could you give it a try?

**Comment by andreyurch** [comment]
Sorry for the late answer!  I will try this week!  Thank you!
