### ISSUE TITLE
Single sample analysis error: plot_contribution()

### ISSUE THREAD

**Issue by coffee-and-genomics** [UMCUGenetics/MutationalPatterns#36]
Hi, I am running into errors when trying to analyze a **single sample VCF** with `MutationalPatterns`.

I am trying to run `plot_contribution()` under the section 

> 4.2.3 Find optimal contribution of COSMIC signatures to reconstruct 96 mutational proﬁles 

in the introduction guide. 

Here is the code that produces the error, along with the
[mut_mat.txt](https://github.com/UMCUGenetics/MutationalPatterns/files/3356303/mut_mat.txt) and 
[cancer_signatures.txt](https://github.com/UMCUGenetics/MutationalPatterns/files/3356304/cancer_signatures.txt) input data that it's using that I've exported to `.txt` for reproducibility:

```
> # Fit mutation matrix to the COSMIC mutational signatures:
> fit_res = fit_to_signatures(mut_mat, cancer_signatures)
> 
> # Plot the optimal contribution of the COSMIC signatures in each sample as a stacked barplot.
> # Select signatures with some contribution
> select = which(rowSums(fit_res$contribution) > 10)
> # Plot contribution barplot
> # FIXME: error - not working
> plot_contribution(fit_res$contribution[select, ], 
+                   cancer_signatures[ ,select],
+                   coord_flip = F, 
+                   mode = "absolute")
Error in names(x) <- value : 
  'names' attribute [3] must be the same length as the vector [1]
```

Compare this with the same command listed in the "Introduction to MutationalPatterns" doc:

```
> # Select signatures with some contribution
> select <- which(rowSums(fit_res$contribution) > 10)
> # Plot contribution barplot
> plot_contribution(fit_res$contribution[select,], 
+ cancer_signatures[,select], 
+ coord_flip = FALSE, 
+ mode = "absolute")
```

The commands `fit_res <- fit_to_signatures(...)` and `select <- which(rowSums(fit_res$contribution) >10)` work, but when I try to run the `plot_contribution()` command, it throws that error.

Is there any clarification on how to use this command for analysis of a single sample? This also isn't the only issue I'm running into when analyzing a single VCF with `MutationalPatterns`. What am I doing wrong? Any insight is appreciated, thanks.

**Comment by FrancisBlokzijl** [comment]
Hi, 

Can you show me what fit_res$contribution[select,] looks like? It should be a matrix (and not a vector)? And is length(select) > 1?

Best,
Francis

**Comment by coffee-and-genomics** [comment]
Hi Francis,

I got it to work by using `as.matrix(fit_res$contribution[select, ]`.

The structure of `fit_res$contribution[select, ]` was a named vector, not a matrix, and it looked like this:

```R
> fit_res$contribution[select, ]
 Signature.1  Signature.7 Signature.10 Signature.21 
  1354.70434     43.89384    737.54308    475.68851 
Signature.28 
  2547.49460 
> str(fit_res$contribution[select, ])
 Named num [1:5] 1354.7 43.9 737.5 475.7 2547.5
 - attr(*, "names")= chr [1:5] "Signature.1" "Signature.7" "Signature.10" "Signature.21" ...
> length(select)
[1] 5
```

***Do you know the reason why it was returning a named vector and not a matrix?***

My full command that worked was this:

```R
plot_contribution(as.matrix(fit_res$contribution[select, ]),
                  cancer_signatures[ ,select],
                  coord_flip = F,
                  mode = "absolute")
```

Thanks for your help.

**Comment by FrancisBlokzijl** [comment]
Hi, 

The reason is that you only have 1 sample. When you select one row or column of a matrix with R, it automatically coerces it into a vector. This can be prevented by setting drop=FALSE. Most of the time people do not analyse 1 sample, so this never came up before.

I'll see if I can add some checks to prevent this problem.

Best,
Francis
