### ISSUE TITLE
Chromosome delimiters not showing in plot_rainfall() plot

### ISSUE THREAD

**Issue by coffee-and-genomics** [UMCUGenetics/MutationalPatterns#37]
Hi, I'm running across an error when plotting plotting the genomic rainfall plot with `plot_rainfall()` and getting some strange errors along with missing plot information.

When I run `plot_rainfall()`, I get the following errors:

```R
> plot_rainfall(vcfs[[1]], title = names(vcfs[1]), chromosomes = chromosomes, cex = 1.5, ylim = 1e+09)
Warning messages:
1: Removed 4542 rows containing missing values
(geom_point). 
2: Removed 20 rows containing missing values
(geom_vline). 
3: Removed 20 rows containing missing values
(geom_text).
```

Some data is still plotted and makes a rainfall plot, but the black vertical chromosome boundary delimiters are missing on the plot ([13--genomic-dist-rainfall.pdf](https://github.com/UMCUGenetics/MutationalPatterns/files/3369005/13--genomic-dist-rainfall.pdf)).

My questions are:

1. Why is `plot_rainfall()` removing some of my data?
2. Why are the black vertical chromosome delimiters not showing up on the plot?

Any help would be appreciated!

**Comment by FrancisBlokzijl** [comment]
Hi,

The behaviour you're seeing is due to how ggplot2 deals with datapoints outside the axis ranges of the plot. Have you tried a larger value for the ylim parameter? Could you play around with it to see if it helps?
How many mutations are in your vcf file? If you have only a few mutations, the intermutation distance will be very big, and then you need a different ylim.

Hope this helps!

Best,
Francis

**Comment by coffee-and-genomics** [comment]
Hi Francis, 

I might have been unclear, but here are the issues I'm having, annotated on my output plot, along with my code: ![image-01](https://user-images.githubusercontent.com/43548130/61246201-e9c91f00-a713-11e9-8746-e8970b3e274d.png)

```R
# 6.1) Rainfall plot ====

# Make rainfall plot of sample 1 over all autosomal chromosomes
# Define autosomal chromosomes
chromosomes = seqnames(get(ref_genome))[1:22] # Goes from chr1-chrM. Numbers >22 start to include e.g. "chr1_GL456210_random" chromosomes. The total number of named chromosomes chromosome categories is 66.
chromosomes
# Make rainfall plot
# FIXME: Chromosome delimiters not showing up
pdf(file = paste0(results_plots_dir, "11--genomic-dist-rainfall.pdf"), width = 12, height = 4)
plot_rainfall(vcfs[[1]], title = names(vcfs[1]), chromosomes = chromosomes, cex = 1.5, ylim = 1e+12)
dev.off()
```

The total number of variants in any single VCF I'm analyzing range from ~2000 to ~11000. I increased the ylim from the default `1e+09` to `1e+12` for example, nothing seems to change as the problem doesn't seem to be the inability to plot variants with increased genomic distance because no new ones appear.

**Issue 1:** The black, vertical, dotted chromosome delineation lines are not appearing, as indicated here: ![image-02](https://user-images.githubusercontent.com/43548130/61246214-f2b9f080-a713-11e9-88ca-11beef77a7cf.png)

***How do I get these vertical lines to appear?***

**Issue 2:** I am getting the following error where it appears the plot is excluding a lot of my variants:

```
Warning messages:
1: Removed 4542 rows containing missing values (geom_point).
2: Removed 20 rows containing missing values (geom_vline).
3: Removed 20 rows containing missing values (geom_text).
pdf
  2
(base)
```

**Not all of the variants are being plotted (see `image-01`) — how do I graphically plot them all?** Doesn't this affect my ability to visually inspect this plot (e.g. for sites of kataegis)?

Any ideas? I'm not sure what to do without delving into the functions themselves. Thanks again for the help.

--Leo

**Comment by FrancisBlokzijl** [comment]
Hi Leo,

Thanks for the clarification.
Can you send me a small vcf file which gives this problem so I can try to reproduce it and hopefully solve it?

Thanks!
Francis

**Comment by coffee-and-genomics** [comment]
Hi Francis,

Here is the VCF file I used on the plot that I posted in my previous reply: [sample-vcf.txt](https://github.com/UMCUGenetics/MutationalPatterns/files/3403164/sample-vcf.txt). It has ~4800 variants. I had to rename it with a `.txt` extension to upload it here, so just add the `.vcf` extension back to it. Let me know if you can reproduce what I'm seeing. Thanks!

- Leo

**Comment by coffee-and-genomics** [comment]
Thank you so much - it looks beautiful now!
