### ISSUE TITLE
error in Loading required package: rtracklayer

### ISSUE THREAD

**Issue by rescuz** [UMCUGenetics/MutationalPatterns#39]
hi,When I run my script,Imet this problem:
Loading required package: rtracklayer
Error in get_data_annotation_contrib_url(type) :
  Install 'BiocManager' from CRAN to get 'BioCann' contrib.url
Calls: head ... available.genomes -> get_data_annotation_contrib_url
 
can you give me some advice?Thanks1

**Comment by FrancisBlokzijl** [comment]
Hi there,

Seems that this is an issue with BSgenome package. Please make sure that you download and install this package and your reference genome of choice properly.

BSgenome_utils[https://rdrr.io/github/Bioconductor/BSgenome/src/R/utils.R]

Best,
Francis
