### ISSUE TITLE
Alternative input formats

### ISSUE THREAD

**Issue by yunguan-wang** [UMCUGenetics/MutationalPatterns#42]
Hi ,firstly, thanks for the nice tool.
I have some processed mutation information in a customized format. 
I tried to add relevant information such as #CHROM, POS, REF, ALT and constructed a 'fake' vcf files with header and mutation info. But I was not able to load these vcf with read_vcf_as_grange function. 
Can you tell me what is the required vcf columns needed for your program?
Thanks!
Yunguan

**Comment by roelj** [comment]
Hi @yunguan-wang,
You need at least the required fields (`CHROM`, `POS`, `ID`, `REF`, `ALT`, `QUAL`, `FILTER`, `INFO`, `FORMAT`), and a `GT` format field.

Also, make sure that your self-created VCF files are valid according to [the specifcation](https://samtools.github.io/hts-specs/VCFv4.3.pdf).
