### ISSUE TITLE
Data format of using this package

### ISSUE THREAD

**Issue by xiw588** [UMCUGenetics/MutationalPatterns#43]
Hi I am wondering if only VCF format could use this package or any other format is also ok?

Thank you.

**Comment by roelj** [comment]
Hi @xiw588 

We only have a `read_vcfs_as_granges` function to load variants.  Which formats would you like to be able to load?

**Comment by xiw588** [comment]
Thank you for your quick response! I only have the compiled data in excel/csv from Oncopanel, and I am wondering if there is any way that I could convert it to and apply this package on it. I could send a sample of my data to you if it helps explain better.

**Comment by roelj** [comment]
Hi @xiw588 

You could try to load the data and transform it into `GRanges`.  We provide example VCF files that you can use to compare the resulting `GRanges`.

I don't know Oncopanel, but it seems to be a rather specific format.  Could you share a sample file, so we can evaluate whether we can write a load function for it?

**Comment by xiw588** [comment]
Hi Roel,

Thank you for your response!
Attached is the data sample that I have at hand. It will be very helpful if
you could give me some idea on how to convert it to VCF.

*Xinan Wang*
*PhD student in Population Health Science *
Harvard T.H.Chan School of Public Health
Mobile: 8578694016
Email: xiw588@mail.harvard.edu

**Comment by xiw588** [comment]
Hi Roel,

Thank you for your response! 
Can you give me an email address so that I could attache the data sample that I have at hand. It will be very helpful if you could give me some idea on how to convert it to VCF.

**Comment by roelj** [comment]
You can find it here:
https://github.com/UMCUGenetics/MutationalPatterns/blob/master/DESCRIPTION#L9

**Comment by roelj** [comment]
This format is too specific to add a generic load function for.  Your best bet is to convert this to the [Variant Call Format](https://samtools.github.io/hts-specs/VCFv4.2.pdf) use the "Genomic Mutation Chromosome Cd" as `CHROM`, "Genomic Mutation Position" as `POS`, "Genomic Mutation Reference Allele" as `REF`, "Genomic Mutation Alternate Allele" as `ALT`, and so on.

VCF is plain-text, so if you follow the document I linked to above, you should be able to make it work. :)

Please not that MutationalPatterns currently only deals with single-nucleotide polymorphisms (SNPs).
