### ISSUE TITLE
Error with mut_type_occurrences function.

### ISSUE THREAD

**Issue by galavots** [UMCUGenetics/MutationalPatterns#48]
Error: 

Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 1555: 'allow.nonnarrowing' is FALSE and the supplied start (142621038) is > refwidth + 1

I am trying to run mutational patterns on the TCGA WES data, but when I get to the mut_type_occurences part I get the above error. Can anybody help in deciphering what's going on? The vcfs have been lifted over to hg19 but otherwise look like other vcfs that have worked perfectly before. 

Thanks

**Comment by sander-vlugter** [comment]
Hi,

Could you tell me if this error is file specific or not? Also could you maybe provide me with a sample file in order to reproduce the error?

**Comment by galavots** [comment]
Hi,
yes it's specific for TCGA files.
Please see in attach screenshot of the error. Of note: you can see there is no match between row number and position, they used to match up but now they don't.
Apologise for not being able to provide a file, to give a reproducible example.

**Comment by sander-vlugter** [comment]
This issue was further addressed via email, this issue will be closed
