### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pdiakumis** [UMCUGenetics/MutationalPatterns#51]
Hi @roelj and others.

Thanks for this great package.
I was under the impression v2.0.0 was close to being released, based on a couple big PRs from late last year including support for DBS and indels, plus a fair few other features (https://github.com/UMCUGenetics/MutationalPatterns/pull/47 and https://github.com/UMCUGenetics/MutationalPatterns/pull/46). I had planned to update our centre's Rmd reports based on this. Have these features been put on hold due to compatibility purposes, or am I missing something?

Kind Regards,
Peter

**Comment by roelj** [comment]
Hi @pdiakumis 

Indeed, Bastiaan's work added a great number of new features, and we were close to putting out a 2.0 release.  Unfortunately Bastiaan left our research group shortly after merging these new features, which made providing support for these features (and integrating them in a Bioconductor-compatible way) difficult.

On a parallel track, Rurika and @FreekManders (outside of our group) built their own DBS and indel features on MutationalPatterns.  We decided to hold off the release and hand over the development and maintenance to Rurika and Freek.

Bastiaan's work is available in the [dbs-indels](https://github.com/UMCUGenetics/MutationalPatterns/tree/dbs-indels) branch, but I don't think it'll be developed further.

Freek's version is available in [his fork](https://github.com/FreekManders/MutationalPatterns).  I think this work will eventually be merged into MutationalPatterns and become the real 2.0 version.

Kind regards,
Roel

**Comment by pdiakumis** [comment]
Suspected something like that had happened.
Thanks very much for those pointers, I'll keep an eye out for the next release.

**Comment by pdiakumis** [comment]
Hi again,
I've noticed quite a few impressive updates from @FreekManders - is there a timeline for Bioconductor release? I wouldn't mind testing it out beforehand if you think it's close to being released.
Kind regards,
Peter

**Comment by FreekManders** [comment]
Hi @pdiakumis,

I'm planning to put the new version in the next bioconductor release (3.12). They haven't published a release schedule yet, but I think the bioconductor release is usually around October. 
The current version of the package on Github should work and has a vignette, so you can test it if you want. However, I will probably still change existing features or add new features, based on feedback from colleagues. (I sent the current version to several colleagues so they can test if it works on their machine and if the vignette/documentation/function names are clear.) So it might be wise to wait a bit longer.

**Comment by pdiakumis** [comment]
Okay, that makes sense. I'll try out the latest master version when I get some time and keep an eye on further major changes.
Thanks very much for keeping this package updated by the way!

**Comment by pdiakumis** [comment]
Closing since I can see the new release is available now on Bioconductor, thanks a lot for your massive effort, much appreciated!
