### ISSUE TITLE
Order of SNV types in mutation matrix

### ISSUE THREAD

**Issue by kittysher** [UMCUGenetics/MutationalPatterns#60]
Hi. I am trying to fit my mutation matrix to COSMIC signatures. I have used the mut_matrix() function on my vcfs successfully, and the SNV type is specified in the rownames of the output matrix. When I load in COSMIC signatures using get_known_signatures() , there are no row names, so I don't know which SBS is which. 
I was assuming that the rownames would be the same to that of the generated mutation matrix. However looking at the order of SNVs in the COSMIC v3.1 GRCh38 SBS download available, the order of SNV types is different to that of the mutation matrix. Please can you confirm the order of SNVs in cosmic from get_known_signatures() 

Many thanks
Kitty

**Comment by FreekManders** [comment]
Hi kittysher,

The order of the signatures from `get_known_signatures()` is the same as that from `mut_matrix()`.
You can see how the data from COSMIC is formatted to have the same order as the `mut_matrix()` output here:
https://github.com/UMCUGenetics/MutationalPatterns/blob/master/inst/scripts/Format_signatures.R

**Comment by kittysher** [comment]
Hi FreekManders,
Thank you very much for the clarification and the quick response :) That helps a lot.
