### ISSUE TITLE
unexpected behaviour of read_vcfs_as_granges()

### ISSUE THREAD

**Issue by ChristofferFlensburg** [UMCUGenetics/MutationalPatterns#61]
Hey!

I ran into a weird behaviour that may be a bug. I found a workaround, so don't need help, but heads up for you if you want to look into it.

This VCF file: (hg38)
```
##fileformat=VCFv4.0
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	COVERAGE	VARIANTREADS	VAF
2	25234373	1	C	T	60	DP=100;AF=0.5
2	25234374	2	G	A	60	DP=100;AF=0.5
```
into

`read_vcfs_as_granges(vcfFile, "temp", genome = 'BSgenome.Hsapiens.UCSC.hg38')`

returns empty.

Removing one of the variants, or even moving them one more base apart, returns as expected.

The workaround was to explicitly specify some more arguments (the documentation really isn't clear what default behaviour is):

`read_vcfs_as_granges(vcfFile, "temp", genome = 'BSgenome.Hsapiens.UCSC.hg38', group='all', type='all')`

returns both variants as expected (by me).
I'm not sure if this is intended behaviour, but it certainly took me some time to track down.

Thanks, great package!
/Christoffer

**Comment by FreekManders** [comment]
Hi,

The variants were combined into a double base substitution, because they were located next to each other. The latest versions give a message about this and how to turn this behaviour off, but the current bioconductor release doesn't do this yet. The dbs was then filtered out, because by default the function only reads in snvs. I will clarify this behaviour in the documentation of the function.

**Comment by FreekManders** [comment]
It's now mentioned in the documentation.

**Comment by sigven** [comment]
On the same note, is there plan to push v3.20 to [BioConda](https://anaconda.org/bioconda/bioconductor-mutationalpatterns) in the near future? 

regards,
Sigve

**Comment by FreekManders** [comment]
I think they pull from bioconductor themselves? I've never put anything on Bioconda myself.

**Comment by sigven** [comment]
Ok, got it. Will just have to wait and see then. Thanks for the swift response.
