### ISSUE TITLE
mut_matrix error

### ISSUE THREAD

**Issue by xiw588** [UMCUGenetics/MutationalPatterns#63]
I applied mut_matrix() on my GRanges object input by a multi-vcf file. The following message showed up. 

_**_The input GRanges and the ref_genome share no seqnames (chromosome names)_

 Do they use the same seqlevelsStyle? An example of how to fix this is show below:
             You can change the seqlevelStyle with: `seqlevelsStyle(grl) = 'UCSC'**_

I checked the seqlevelStyle and it is UCSC, do you have an idea of how to solve this issue? 

Thank you for your help.

**Comment by FreekManders** [comment]
Hi,

It seems the reference genome and the GRangesList don't share any seqnames (chromosomes). Can you check what the seqnames of both your GRanges and the reference genome are with:
```
as.vector(seqnames(grl[[1]]))
seqnames(BSgenome::getBSgenome(ref_genome))
```

**Comment by xiw588** [comment]
Hi, Thank you very much for your help. I checked the seqnames for both and it seems that the issue occurs due to the chromosome names didn't match exactly, as grl had just numbers but ref_genome had chr+numbers. Do you know if we could modify the seqnames in grl? 

Thank you.

**Comment by FreekManders** [comment]
```seqlevelstyle(grl) = "UCSC"```, should add the "chr" to the numbers.
