### ISSUE TITLE
How to deal with 'Intron' and 'IGR' variants from WES data when fitting signatures?

### ISSUE THREAD

**Issue by lincj1994** [UMCUGenetics/MutationalPatterns#68]
Hi. I want to fit signatures for WES sequencing data. But I dont know how to deal with 'Intron' and 'IGR' variants for WES data when fitting signatures. (About 40 percent of the variants were Intron).
Keep it or remove it. Thank you

**Comment by FreekManders** [comment]
Signature analysis is often done on WGS data, so I think it is fine to keep all the variants in this case.
