### ISSUE TITLE
fit_to_signatures_strict: Error in if (delta <= max_delta) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by lincj1994** [UMCUGenetics/MutationalPatterns#69]
```
> CBCGASBS_refit <- fit_to_signatures_strict(CBCGASBS_mat, as.matrix(COSMICSBS_BRCA), max_delta = 0.002, method = 'best_subset')
Error in if (delta <= max_delta) { : 
  missing value where TRUE/FALSE needed
```
Hi. I want to refit COSMIC signatures using best_subset method but it returned an error. I dont understand it since I have assigned the max_delta.

**Comment by FreekManders** [comment]
That's strange. Do the examples of this function also give an error? (See ?fit_to_signatures_strict) for the examples.
