### ISSUE TITLE
get_mut_type for indels results in empty GRangesList

### ISSUE THREAD

**Issue by kristianunger** [UMCUGenetics/MutationalPatterns#72]
Hi there,

when I try to get get indels using the get_mut_type function from a Mutect2 (tumor/normal pairs) vcf (mouse) I get an empty granges objects although there should be indels by manually inspecting the vcf. SNVs load fine and DBS also is empty. The reference genome I was using for Mutect2 analysis was GRCm38.p6 which should be fine with BSgenome.Mmusculus.UCSC.mm10. Can you give me direction what could go wrong?

Many thanks,

Kristian

**Comment by FreekManders** [comment]
Hi Kristian,

The `read_vcfs_as_granges` function by default only reads the SNVs. Did you set it to `type = "all"`  to include all variants? Additionally, what version of the package are you using?

**Comment by kristianunger** [comment]
Thank you!
I am using the latest BioC version.

Adding type = "all" did the trick.

I followed the docu https://bioconductor.org/packages/release/bioc/vignettes/MutationalPatterns/inst/doc/Introduction_to_MutationalPatterns.html#load-example-data-indels-dbss-and-mbss and used the function as described for loading SNVs only.
