### ISSUE TITLE
work with MAF files

### ISSUE THREAD

**Issue by crazyhottommy** [UMCUGenetics/MutationalPatterns#8]
Hi,

Now the tool accepts VCF files, I have bunch of MAF files, could you please make the tool parse it as well?

Thanks,
Tommy

**Comment by roelj** [comment]
Hi @crazyhottommy.  Why don't you convert the MAF files to VCFs? [This tool](https://github.com/mskcc/vcf2maf) seems to be able to do that.

**Comment by crazyhottommy** [comment]
Thanks! I did that.
